### ISSUE TITLE
Shadow Compare button throws NPE during shadowing operations

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#259]
**Describe the issue**: 
The `ShadowControlPane` class has a _Compare_ button which displays a `ShadowCompareFrame` containing a `ShadowComparePane` showing comparisons between Remote CCS and local (PC2) run results.   The `ShadowCompareFrame` is only displayable when there already exists a `ShadowController` (which gets created when the _Start Shadowing_ button is pressed).  

Once Shadowing has been started, pressing _Compare_ at any time should display a comparison of all those runs currently in the system.  However, at certain times while shadowing is enabled, pressing the _Compare_ button throws an NPE (see below). The exception is being thrown in method `ShadowController.getJudgementComparisionInfo()`.

Note that this issue is NOT the same as Issue #49, which is an issue of throwing an NPE **while shadowing has been disabled**.  THIS issue is something which happens while shadowing is _enabled_.  (It is of course possible that the two issues are related, perhaps sharing an underlying root cause... but so far that doesn't seem to be the case.)

**To Reproduce**: 
- Start a PC2 Server configured to point to a Remote CCS to be shadowed -- including that the server is configured with the exact same contest settings (problems, languages, etc.) as the Remote CCS.
- Start at least one AJ, configured to judge the problem(s) to be fetched from the Remote CCS (the CCS being shadowed).
- Ensure that there exists a Remote CCS already configured to support CLICS Contest API connections.  The Remote CCS should _already have a large number of events queued up and ready to send to its Event Feed_.  (In other words, don't try to run the Remote CCS in real time; exposing the bug requires having the Remote CCS send _large numbers of events_ at once.)
- Start an Event Feeder client.
- On the EF client, click _Start Shadowing_.  Observe that the Shadow EF client is displaying large numbers of trace/debug outputs on its console.
- Click the _Compare_ button on the Shadow EF client.

**Expected behavior**: 
The Shadow EF client should display a _ShadowCompareFrame/Pane_ showing a comparison of whatever runs have been received from the Remote CCS so far.

If there is an NPE or other Exception while creating the compare data or while attempting to show the _ShadowCompareFrame
a dialog should appear with the Exception and some context information.

The exception should be logged (if it isn't being logged now).

**Actual behavior**: 

An exception is thrown to the console and no _ShadowCompareFrame or any other dialog is shown.

The Shadow EF client throws a NullPointerException, like
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.csus.ecs.pc2.shadow.ShadowController.getJudgementComparisonInfo(ShadowController.java:445)
	at edu.csus.ecs.pc2.ui.ShadowComparePane.getUpdatedResultsTableModel(ShadowComparePane.java:179)
	at edu.csus.ecs.pc2.ui.ShadowComparePane.<init>(ShadowComparePane.java:95)
	at edu.csus.ecs.pc2.ui.ShadowCompareFrame.<init>(ShadowCompareFrame.java:24)
	at edu.csus.ecs.pc2.ui.ShadowControlPane$7.actionPerformed(ShadowControlPane.java:594)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Environment**:
 - Issue was observed when running a Shadow EF client under Windows 10, connected to a remote Kattis system feeding the NADC21 contest at URL https://nadc21.kattis.com/clics-api/contests/nadc21/event-feed.
 - PC2 Version:   The PC2 server was running build 6192 on AWS machines.  The Shadow EF client was running a local build within Eclipse on my Windows 10 machine which had been updated by pulling from the Develop branch.

**Additional context**: 
It appears that the exception may be a result of pressing the button at the exact moment when new runs are being received by the shadowing system.  In particular, method `getJudgementComparisonInfo()` invokes `InternalContest.getRuns()`, which in turn invokes `RunList.getList()`.  Method `getList()` calls `Hashtable.values()` (on the `runHash` Hashtable) to get a Collection of runs in the "run list".  `getList()` then calls `toArray(new Run[size()])` to convert the Collection (list of runs) to an array.  

The JavaDoc for method `Hashtable.values()` says:
```
Returns a Collection view of the values contained in this map.The collection is backed by the map, so changes to the map
are reflected in the collection, and vice-versa. If the map is modified while an iteration over the collection is in
progress (except through the iterator's own remove operation),the results of the iteration are undefined. 
```
If the call to `toArray()` is using an interator on the Collection and a new run comes in during this time, it's possible that the "undefined results of the iteration" might include inserting a null value into the array.  This in turn would cause an NPE when the array was subsequently processed in the loop (around line 343) in method `getJudgementComparisonInfo()`.  This would imply that accesses which update the RunList should be blocked during the time that `getList()` is building the array which it is returning.

**Comment by lane55** [comment]
" This would imply that accesses which update the RunList should be blocked during the time that getList()"  This issue cannot be a new one, would using a thread safe structure/collection solve this root cause?
