### ISSUE TITLE
In Compare Primary with model Report there are parsing and other errors

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#570]
**Describe the issue**: 

In Compare Primary with model Report, fails to parse:
* languages
* problems

See Additional context for exceptions

In Compare Primary with model Report, fails to parse "languages" extensions JSON
Exception in report: Can not deserialize instance of java.lang.String out of START_ARRAY token

"extensions":["c"]

{"token":"1576","id":"c","type":"languages","data":{"id":"c","name":"C","extensions":["c"],"filter_compiler_files":true,"allow_judge":true,"time_factor":1.0,"entry_point_required":false,"entry_point_name":null},"time":"2022-10-21T12:35:37.228+02:00"}

In Compare Primary with model Report, fails to parse "staetment" array JSON

"statement":[{"href":"contests/bapc2022/problems/adjustedaverage/statement","mime":"application/pdf","filename":"A.pdf"}],
"test_data_count":36},"time":"2022-10-21T12:35:44.076+02:00"}

**To Reproduce**: 

Run admin on bapc2022  (https://judge.gehack.nl/api/contests/bapc2022)
Run Compare Primary with model Report

**Expected behavior**: 

prints comparison

**Actual behavior**: 

throws java.lang.IllegalArgumentException:

**Environment**: 

**Log Info**:  

**Screenshots**:  

**Additional context**: 

\*\* Compare Primary with model Report

Shadow mode      : Yes
CCS URL          : https://judge.gehack.nl/api/contests/bapc2022
CCS Login        : pc2

Exception in report: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: edu.csus.ecs.pc2.core.imports.clics.CLICSLanguage["extensions"])
java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: edu.csus.ecs.pc2.core.imports.clics.CLICSLanguage["extensions"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3288)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3214)
	
   Exception in report: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: edu.csus.ecs.pc2.core.imports.clics.CLICSProblem["statement"])
java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: edu.csus.ecs.pc2.core.imports.clics.CLICSProblem["statement"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3288)

**Comment by lane55** [comment]
closing, merged
