### ISSUE TITLE
Better validation of loaded sample and secret data should be done during --load

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#668]
**Describe the issue**:
It is very easy to import incorrect input and answer files during a server `--load `operation.    

**To Reproduce**: 
There are a couple use cases than can cause incorrect data files to be imported for a problem's data files.
1) If there is no corresponding `.ans` for for a` .in `file (a check should be made: `inputFileNames.length == answerFileNames.length` during data importing.
2) If a data import folder does not have the files listed in sorted order, then a mismatch can occur between `.in `and` .ans` files.   Perhaps the answer file names should be generated based on the input file names instead of creating two independent lists and hope they match up.
3) If a data import folder has input files that are, say, **c.in**, **b.in** and **a.in** and the answer files supplied are **d.ans**, **e.ans**, **a.ans** (due to an error by the problem creator), this will not be caught as a potential problem.

**Expected behavior**: 
If any sort of mismatch occurs between `.in `and `.ans `files, it should be reported as an import error.

**Actual behavior**:
If mismatches or missing ans files are in a data import folder, it's possible that the wrong files may be loaded.

**Environment**: 
Version         : 9.9build 20230119
Build Date      : Thursday, January 19th 2023 13:39 UTC
Build Number    : 6415
OS              : Linux 5.15.0-56-generic (amd64)
Java Version    : 17.0.5
Version 9.9build 20230119 (Thursday, January 19th 2023 13:39 UTC) Java ver 17.0.5 build 6415 Linux 5.15.0-56-generic (amd64) 

**Log Info**:  

**Screenshots**:  

**Additional context**:  See discussion for PR #618

**Comment by lane55** [comment]
Test 2 - use mismatching in and ans files
Passes: an exception is thrown and server halts.

Expected an exception to be thrown and server to not start (fatal error)

restore samps\contests\valtest\config\sumit\data\secret\sumit3.ans if needed

in sample 4, samps\contests\valtest\config\sumit4\data\secret

create judges files c.in, b.in, a.in, d.ans, e.ans, a.ans 

cp sumit.in c.in
cp sumit.in b.in 
cp sumit.in a.in 
cp sumit.ans d.ans
cp sumit.ans e.ans
cp sumit.ans a.ans 
rm -f sumit*

use: --load valtest

Actual

edu.csus.ecs.pc2.core.exception.YamlLoadException: Missing b.ans file for sumit4 in C:\repos\lane55fork\samps\contests\valtest\config\sumit4\data\secret
	at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.checkForFile(ContestSnakeYAMLLoader.java:3013)
	at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.loadCCSProblemFiles(ContestSnakeYAMLLoader.java:2874)
	at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.loadProblemInformationAndDataFiles(ContestSnakeYAMLLoader.java:1365)

**Comment by lane55** [comment]
Note that a test was run and files are loaded in ascending lexical order.

**Comment by lane55** [comment]
All tests done using

**Comment by johnbrvc** [comment]
Having tried each case and traced through the code, I can confirm that all these cases, as @lane55 points out (correctly) cause an exception.  The code is a bit misleading in that it first get two arrays of file names: `*.in` and `*ans`, then it sorts them and checks the array lengths are the same.  At that point it then goes through each element of the file name arrays, and adds them to the test cases for the problem.  It **THEN** creates a new `".ans"` file name based on the input `".in"` file name, and checks for existence of both of those files.  It's misleading because it had just added a potentially incorrect file name from the answer file name array to test cases.  It _does_ catch the problem because if the newly generated `".ans"` file is not found, then it will cause an exception and exit.

As for the names potentially being out of order, this was fixed when the `Arrays.sort(xxx)` of each array was added, so that problem is addressed as well.  

So, these are non-issues in terms of functionality at this point.

Some of the issues were taken from the discussion of #618 but #618 fixed them.

I think we can mark this issue as being a non-issue at this point.
