### ISSUE TITLE
YAML load of freeze time may convert to minutes rather than using the yaml value.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#67]
**Describe the issue**:

When a scoreboard-freeze-length value of 1:00:00 is read in from a YAML file, the importer incorrectly records this time as 3600 -- i.e., in seconds.   This causes any code which is processing the value and expecting it to be in CLICS format to
an invalid format.

**To Reproduce**: 

 * Create a contest.yaml file with "scoreboard_freeze_length: 1:00:00".
   * (or just use samps/contests/sumithello, which already has an equivalent value in it)
 * Start a server reading the YAML file (use --load option)
 * Start an Admin and look at ConfigureContest>Settings: Scoreboard Freeze Length

**Expected behavior**: 

Scoreboard Freeze length should be displayed in "hh:mm:ss form" as 1:00:00 

**Actual behavior**: 

Scoreboard freeze time is "3600" (it converts the time in hh:mm:ss form into minutes)

**Workaround**: 

Use the value 01:00:00 instead of 1:00:00

**Environment**: 

Win10 with Java 1.8.0_201, but I'm pretty sure it applies to all environments.

**Additional context**: 

See Bugzilla [bug 1612](https://pc2.ecs.csus.edu/bugzilla/show_bug.cgi?id=1612)

**Comment by troy2914** [comment]
also to add to this the spec calls for
Relative times (type RELTIME in the specification) are strings containing human-readable time durations, given in a slight modification of the ISO 8601 extended time format: (-)?(h)*h:mm:ss(.uuu)?

unclear why the - is wanted,  but we are missing support of .uuu

**Comment by troy2914** [comment]
btw in my testing "1:00:00" was working ,  though " 1:00:00" was not.   Also grumble, the Model stores this a String,  why oh why....

**Comment by clevengr** [comment]
> btw in my testing "1:00:00" was working , though " 1:00:00" was not. Also grumble, the Model stores this a String, why oh why....

I could not get either "1:00:00" or " 1:00:00" to work.  The latter produced "3600" in the Settings (as described in the original Issue report), while the former threw an exception:

```
edu.csus.ecs.pc2.core.exception.YamlLoadException: Parse error at line=10 column=1 message=could not find expected ':'
        at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.loadYaml(ContestSnakeYAMLLoader.java:106)
        at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.fromYaml(ContestSnakeYAMLLoader.java:390)
        at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.fromYaml(ContestSnakeYAMLLoader.java:158)
        at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.fromYaml(ContestSnakeYAMLLoader.java:130)
        at edu.csus.ecs.pc2.imports.ccs.ContestSnakeYAMLLoader.initializeContest(ContestSnakeYAMLLoader.java:3230)
        at edu.csus.ecs.pc2.core.InternalController.handleCDPLoad(InternalController.java:2786)
        at edu.csus.ecs.pc2.core.InternalController.initializeServer(InternalController.java:1052)
        at edu.csus.ecs.pc2.core.InternalController.authenticateFirstServer(InternalController.java:1194)
        at edu.csus.ecs.pc2.core.InternalController.login(InternalController.java:782)
        at edu.csus.ecs.pc2.ui.LoginFrame.attemptToLogin(LoginFrame.java:446)
        at edu.csus.ecs.pc2.ui.LoginFrame$5.actionPerformed(LoginFrame.java:401)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener$Actions.actionPerformed(BasicButtonListener.java:303)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
        at java.awt.Component.processEvent(Component.java:6316)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: while scanning a simple key
 in 'reader', line 8, column 1:
    scoreboard-freeze-length:1:00:00
    ^
could not find expected ':'
 in 'reader', line 10, column 1:
    languages:
    ^

```

**Comment by troy2914** [comment]
btw, I literally meant "1:00:00"  with the quotes resulted in the freeze time as showing as 1:00:00

**Comment by troy2914** [comment]
It seems the yaml parser is converting that 1:00:00 to 3600, the JSONTool handles the non-colon time as a long.   The admin page and maybe the scoreboard does not do that conversion.
