### ISSUE TITLE
WTI scoreboard is blank or shows all teams from all divisions

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#680]
**Describe the issue**: 

A team WTI scoreboared with 3 divisions should show just
the team's divisions rankings/runs.  The scoreboard shows
all teams in all divisions.

Under certain cirsumstances the WTI scoreboard is blank
and throws an exception, found in the log and below
Log Info section.

**To Reproduce**: 

Use tc1 CDP at PacNWSpring2023/testcontest1/config

start server with tc1
start wti 
login as team101
click Scoreboard

**Expected behavior**: 

Should show only teams from D1

**Actual behavior**: 

Shows all 47 teams from all 3 divisions

**Environment**: 

Linux ip-172-16-1-46 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

**Log Info**:  

The scorboard2's scoring settings for Minute penalty is null

Caused by: java.lang.NumberFormatException: Cannot parse null string
    at java.base/java.lang.Integer.parseInt(Integer.java:630)
    at java.base/java.lang.Integer.parseInt(Integer.java:786)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getPropIntValue(DefaultScoringAlgorithm.java:248)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getPenaltyPointsPerYesMinute(DefaultScoringAlgorithm.java:278)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.calcProblemScoreData(DefaultScoringAlgorithm.java:208)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.generateStandingsValues(DefaultScoringAlgorithm.java:947)
    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getStandings(DefaultScoringAlgorithm.java:447)
    at controllers.ContestController.getStandings(Unknown Source)

**Screenshots**:  

**Additional context**:

**Comment by lane55** [comment]
The team's WTI scoreboard, like the scoreboard standings are per division.   So a team's scoreboard should
show all teams from a divisions.

For example in the contest there are 5 groups in D1:
21627	British Columbia - UBC D1
21624	Washington - UW Tacoma D1
21626	Oregon - George Fox D1
21623	California - Chico State D1
21625	Hawaii - BYUH D1

Team 101 is in D1, so on its scoreboard should be all teams that are in the
five groups above.

At this time the only way to identify the team's division is by the D# in the team's group name.

**Comment by lane55** [comment]
For the NPE (Log section) the scoring properties are not int the input properties to the  ContestController dsa.getStandings
Below shows the properties present (none of which are scoring properties)

230207 201240.815|INFO|qtp787738361-22|log|debug 22 XL debug 22 props {Output Public HTML dir=/home/ubuntu/pc2/wti/WebTeamInterface-1.1/WebContent/WTI-UI/scoreboard, Output HTML dir for Judges=/home/ubuntu/pc2/wti/WebTeamInterface-1.1/WebContent/WTI-UI/secret22}

**Comment by lane55** [comment]
closing ticket fixed and merged in PR 682
