### ISSUE TITLE
Can not generate valid cacerts.pc2 for Event Feed web services on newer JRE's 

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#687]
**Describe the issue**: please provide a clear and concise description of what the bug is.  
With newer JRE's, when the cacerts.pc2 certificate file needs to be created (IE it doesn't exist), pc2ef throws an Illegal Access exception and an invalid SSL certificate is produced.  As a result, the web services endpoints to not work since a remote host can not establish a secure
connection.

**To Reproduce**: 
On the ICPC 2022 WF Image:
1) Load a contest.
2) Start pc2 server
3) make sure there is a feeder account created
4) start pc2ef from a folder where there is no cacerts.pc2 file
5) Start the web services feeds
6) observe the standard output produced (there will be an exception report as shown in the logs below)

**Expected behavior**: 
A valid certificate (cacerts.pc2) should be created.

**Actual behavior**: 
An invalid certificate is created.

**Environment**:
Version         : 9.9build 20230128
Build Date      : Saturday, January 28th 2023 14:48 UTC
Build Number    : 6437
OS              : Linux 5.15.0-56-generic (amd64)
Java Version    : 17.0.5

**Log Info**: 
```
java.lang.IllegalAccessException: class edu.csus.ecs.pc2.services.eventFeed.WebServer cannot access class sun.security.tools.keytool.CertAndKeyGen (in module java.base) because module java.base does not export sun.security.tools.keytool to unnamed module @62bd2070
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at edu.csus.ecs.pc2.services.eventFeed.WebServer.createKeyStoreAndKey(WebServer.java:129)
        at edu.csus.ecs.pc2.services.eventFeed.WebServer.startWebServer(WebServer.java:186)
        at edu.csus.ecs.pc2.ui.WebServerPane.startWebServer(WebServerPane.java:164)
        at edu.csus.ecs.pc2.ui.WebServerPane.access$000(WebServerPane.java:42)
        at edu.csus.ecs.pc2.ui.WebServerPane$1.actionPerformed(WebServerPane.java:133)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-02-13 10:34:34.495:INFO::AWT-EventQueue-0: Logging initialized @15702ms
Mon Feb 13 10:34:34 EST 2023 Starting /starttime web service
Mon Feb 13 10:34:34 EST 2023 Starting /fetchRun web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/scoreboard web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/languages web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/teams web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/groups web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/organizations web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/judgement-types web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/clarifications web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/submissions web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/problems web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/judgements web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/runs web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/event-feed web service
Mon Feb 13 10:34:34 EST 2023 Starting /contest/state web service
Mon Feb 13 10:34:34 EST 2023 Loading /home/pc2/realm.properties
2023-02-13 10:34:34.658:INFO:oejs.Server:AWT-EventQueue-0: jetty-9.2.11.v20150529
2023-02-13 10:34:35.018:INFO:oejsh.ContextHandler:AWT-EventQueue-0: Started o.e.j.s.ServletContextHandler@548fe051{/,null,AVAILABLE}
2023-02-13 10:34:35.075:INFO:oejs.ServerConnector:AWT-EventQueue-0: Started ServerConnector@1250e5c9{SSL-HTTP/1.1}{0.0.0.0:50443}
2023-02-13 10:34:35.075:INFO:oejs.Server:AWT-EventQueue-0: Started @16284ms
Mon Feb 13 10:34:35 EST 2023 Started web server on port 50443
```
**Workaround **:
Run the event feed module on JRE 1.8 or Java 8 

**Screenshots**:  
![image](https://user-images.githubusercontent.com/5657363/218515195-81637125-f559-4f92-bc8b-c63391699723.png)

**Additional context**: 
Browsers will report an "End of File" error when trying to connect to a feeder that is using a bad certificate.
There is a fair amount of discussion on google about the issue: https://stackoverflow.com/questions/29060064/sun-security-x509-certandkeygen-and-sun-security-pkcs-pkcs10-missing-in-jdk8
This error is caused by the fact that sun.security module is no longer supported in Java 16 and higher. Try using the methods described here: https://openjdk.java.net/jeps/396  [JohnB Note: I did not read the link suggestion - I pulled it from a forum]

**Comment by johnbrvc** [comment]
@troy2914  suggested that we already have this:
```
            // and this is why you are not suppose to use sun classes
            if (System.getProperty("java.version").matches("^1\\.[67]\\..*")) {
                certAndKeyGen = "sun.security.x509" + ".CertAndKeyGen";
            } else {
                // Java 8 moved the CertAndKeyGen class to sun.security.tools.keytool
                certAndKeyGen = "sun.security.tools.keytool" + ".CertAndKeyGen";
            }

```
that can be extended for newer…

**Comment by johnbrvc** [comment]
All of PC2 should probably be brought up-to-date with (built with) the same JDK/JRE we use on the WF image...

**Comment by troy2914** [comment]
Also work around:  

```
sudo -i
cd /etc/letencrypt/certs/live/$fqdn
openssl pkcs12 -export -out cds.pfx -inkey privkey.pem -in fullchain.pem -name "CDS"
keytool -importkeystore -srckeystore cds.pfx -destkeystore cacerts.pc2 -srcstoretype pkcs12 -alias CDS
# cp resulting cacerts.pc2 to the pc2 ef jake dir
```

see code/documentation for what passwords should be used.

**Comment by troy2914** [comment]
> **Additional context**: Browsers will report an "End of File" error when trying to connect to a feeder that is using a bad certificate. There is a fair amount of discussion on google about the issue: https://stackoverflow.com/questions/29060064/sun-security-x509-certandkeygen-and-sun-security-pkcs-pkcs10-missing-in-jdk8 This error is caused by the fact that sun.security module is no longer supported in Java 16 and higher. Try using the methods described here: https://openjdk.java.net/jeps/396 [JohnB Note: I did not read the link suggestion - I pulled it from a forum]

and said java.net page has this bit:
Code that uses the sun.security.tools.keytool.CertAndKeyGen class to generate self-signed certificates. There is not yet a standard API for this functionality (though a [request has been submitted](https://bugs.openjdk.java.net/browse/JDK-8058778)); in the mean time, developers can use existing third-party libraries that include this functionality.


of course JDK-8058778 has no activity on it for years.

**Comment by troy2914** [comment]
> third-party libraries

And apparently one of those third-party libraries is:
org.bouncycastle:bcpkix-jdk15on-1.68
per https://medium.com/@lbroudoux/generate-self-signed-certificates-in-pure-java-83d3ad94b75

**Comment by troy2914** [comment]
> > third-party libraries
> 
> And apparently one of those third-party libraries is: org.bouncycastle:bcpkix-jdk15on-1.68 per https://medium.com/@lbroudoux/generate-self-signed-certificates-in-pure-java-83d3ad94b75

where 1.70 is the current version per https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on/1.70

**Comment by troy2914** [comment]
> > > third-party libraries
> > 
> > 
> > And apparently one of those third-party libraries is: org.bouncycastle:bcpkix-jdk15on-1.68 per https://medium.com/@lbroudoux/generate-self-signed-certificates-in-pure-java-83d3ad94b75
> 
> where 1.70 is the current version per https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on/1.70

but it's noted the bouncycastle is bloated.  and on https://stackoverflow.com/questions/71441994/how-to-generate-self-signed-certificate-in-java-with-jdk17
it was stated:


The ability to sign certificates is not part of a standard Java library or extension.

A lot of the code that is needed to do it yourself is part of the core. There are classes to encode and decode X.500 names, X.509 certificate extensions, public keys for various algorithms, and of course, for actually performing the digital signature.

Implementing this yourself is not trivial, but it is definitely doable—I probably spent 4 or 5 full days the first time I made a working prototype for certificate signing. It was a fantastic learning exercise for me, but it's hard to justify that expense when there are usable libraries available for free.

**Comment by troy2914** [comment]
heh, or we can give on self-signed certs and go with https://github.com/shred/acme4j to talk to Let's Encrypt.

**Comment by troy2914** [comment]
> but it's noted the bouncycastle is bloated. 

was noted as 5MB 13 months ago.    Though 5 MB is not much compared with 17 MB we currently have.

**Comment by clevengr** [comment]
> All of PC2 should probably be brought up-to-date with (built with) the same JDK/JRE we use on the WF image...

The problem with this is that we lose one of the long-term goals of PC2: the ability for users to run it using any (reasonable) version of Java.  (We can debate whether a given version is "reasonable", but it _doesn't_ seem reasonable to say that every user must upgrade their Java to what we're using in the latest WF image...)
