### ISSUE TITLE
Adding a new problem from the GUI causes an NPE preventing the addition of the problem

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#778]
**Describe the issue**:
New problems can not be added using the GUI.  An **NPE** occurs during the initialization of the new problem.

**To Reproduce**:
Try to add a new problem from the "`Problems`" tab on an administrator account by pressing the "`Add`" button.
Nothing happens.

**Expected behavior**: 
A dialog should appear that allows the user to fill in the information for the new problem.  

**Actual behavior**:
Nothing happens when the `Add `button is pressed; an NPE is generated and the dialog to add the problem never appears.

**Environment**: 
```
Version         : 9.9build 20230523
Build Date      : Tuesday, May 23rd 2023 03:28 UTC
Build Number    : 6607~develop
OS              : Linux 5.15.0-56-generic (amd64)
Java Version    : 17.0.5


```
**Log Info**:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "edu.csus.ecs.pc2.core.model.Problem.getSandboxType()" because "this.problem" is null
        at edu.csus.ecs.pc2.ui.EditProblemSandboxPane.setProblem(EditProblemSandboxPane.java:138)
        at edu.csus.ecs.pc2.ui.EditProblemPane.setProblem(EditProblemPane.java:2275)
        at edu.csus.ecs.pc2.ui.EditProblemFrame.setProblem(EditProblemFrame.java:77)
        at edu.csus.ecs.pc2.ui.ProblemsPane.addProblem(ProblemsPane.java:562)
        at edu.csus.ecs.pc2.ui.ProblemsPane$4.actionPerformed(ProblemsPane.java:553)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Screenshots**: 

**Additional context**: 
The `EditProblemSandboxPane `expects the problem object passed in to be non-null.  When a new problem is added, null is passed since the problem does not yet exist.

**Comment by lane55** [comment]
Reproduced this bug.  The stack trace is printed to stdout but not to log.

**Comment by lane55** [comment]
Add requirement:  print stack trace to (admin) log.

**Comment by lane55** [comment]
Line where NPE occured
