### ISSUE TITLE
Test units fail when run as part of a package build on Windows/MacOS

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#888]
**Describe the issue**: 
It has been observed that several test units fail (see **Log Info** below) when run as part of the build process (as opposed to running them individually).  This only happens if the system you are running has the default executable path set so that the _JDK 1.8/JRE1.8_ is not before any newer version of a JDK or JRE.  You can determine this if you create a command prompt and type "`java -version`", for example:
```
C:\Windows\System32>java -version
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
```
Note this is NOT a problem for the CI _Workflows_ in **Github**, since the path only contains the **Java 1.8 JDK/JRE**.

**To Reproduce**:
On a system where the **JDK/JRE 1.8** is NOT first on the path:
1) Clone a new copy of the latest develop branch
2) Create a new Eclipse project and import the newly cloned branch.
3) Right click on the "`build.xml`" and choose "_Run as..._"
4) Choose only: "**JarSkipBuldSubprojects**".  This will cause Eclipse to build PC2 only, and then run all the JUnits.
5) Observe that some tests fail.

**Expected behavior**: 
 All JUnit tests should pass.

**Actual behavior**: 
Several JUnit tests fail.  See Log Info below.

**Environment**: please complete the following information:
Windows 11.0
pc2v9.10 develop
JDK 1.8.0_321 + JDK-11.0.16.101

**Log Info**:  
[juniterrors..txt](https://github.com/pc2ccs/pc2v9/files/13601855/juniterrors.txt)

**Screenshots**:

**Additional context**: 
The problem stems from the fact that the Ant JUnit task specified in the build.xml file:
```
		<junit errorProperty="test.failed" failureProperty="test.failed" fork="yes">
                        <jvmarg value="-Djdk.crypto.KeyAgreement.legacyKDF=true"/>

```
If this is changed to:
```
		<junit errorProperty="test.failed" failureProperty="test.failed" fork="yes" jvm="C:/Program Files/Java/jdk-1.8/bin/java.exe">
                        <jvmarg value="-Djdk.crypto.KeyAgreement.legacyKDF=true"/>

```
Then the **JUnits** will all run correctly.  It seems that the _Ant JUnit_ task (according to multiple sources on the internet) do not listen to the Eclipse's default JRE, rather, it just uses "java" as the command to run the JUnit tests.  Whatever "java" comes up first on your default path is used to run the JUnit tests.  The "jvm" attribute in for the Ant junit task allows you to specify a different JVM to use.  Obviously, the path to java.exe should be whatever it is on the target system.  The one above is just an example from my system.

**Comment by clevengr** [comment]
This is an excellent overview and detailed explanation of the problem.  I'm wondering how it's possible that this (apparently) just _suddenly_ started happening; I've been running `package.xml` on multiple local machines regularly for many months (years?) and have never seen this JUnit failure (although I guess it's possible that I've always been defaulting to an Ant target that skips the Tests...)

In any case, I guess the real question is:  what's the solution?  Or perhaps, "Is it possible there _is NO solution_?"   I think what we want is to have a single build-script (i.e., `package.xml` and the scripts it in turn imports) that will work on everybody's local platform.  But it's not clear to me at the moment how we can even accomplish that, since hard-coding a JDK path into the Ant <junit> task in the script clearly isn't going to be likely to work the same on everybody's machine...  Not sure whether there is a clean fix for this (?)

**Comment by johnbrvc** [comment]
Further research reveals the **REASON** that some **JUnit** tests were failing.  It seems any test that uses the `Executable `class to compile and run a java program will use Eclipse's default **javac** compiler.  Since this is "**javac 17.0.1**", it creates `.clas`s files with class file version 61 (For java 17).  Java 8 (1.8) class files are version 52.  When the **JUnit** went to execute the class files produced, the following error is generated:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: PracticeA has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
When the suggested "fix" above was added to the **build.xml** (`<junit ... jvm="xxx">`), this forced the execution environment for the _Ant JUnit task_ to use Java 1.8 utilities (derived from the path of the "**java.exe**" in the '**jvm**' attribute), which produces a class file with the correct version (52).  In addition, when you run a **JUnit** by hand, it uses the JVM information you have set in Eclipse, which is 1.8.  Remember, the _Ant JUnit task_ runs as a separate entity from Eclipse, so it does not know what settings you have in eclipse for the Build environment.  Although the _Ant JUnit task_ is running in a Java 1.8 JVM, when `Execute `invokes the "**javac.exe**" compiler to build java programs, it uses whatever **javac.exe** it finds first on the **PATH** (Java 17 in this case).

I am trying now to figure out how to set the **PATH** environment variable in Eclipse so when it executes the _Ant Junit task_, it uses a **PATH** where the 1.8 **javac.exe** comes first.

**Comment by johnbrvc** [comment]
More info and the specific cause of this problem.  When you install Eclipse using the eclipse installer (as opposed to unzipping a zip of Eclipse), the installer creates a folder called: `C:\Users\YOURUSERNAME\.p2`  This folder contains a full JDK (17) in the `C:\Users\YOURUSERNAME\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657\jre` It seems that Eclipse adds this to the BEGINNING of the PATH variable, causing any thing it forks off to use its "`jre\bin`" folder, which contains "**java.exe**" and "**javac.exe**".  The problem here is "**javac.exe**"; when PC2 runs JUnit tests that require compiling java code, it will build it using the "**javac.exe**" in the ".p2" folder (IE Version 17).  Then, when Ant goes to RUN it using the Java 1.8, it gives the error described above (bad **.class** file version).  When a '**_jvm_**' is specified on the _Ant JUnit task_, this overrides the **PATH** and it uses the JDK found at the same path as the JVM (this is why it works when you add the "**jvm**" to the `build.xml `<**junit**> key.  As a test, I renamed `C:\Users\John Buck\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657\jre\bin\bin\javac.exe` to `C:\Users\John Buck\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657\jre\bin\javac.exexxx` and lo and behold, the JUnit tests now run just fine (without the change to the build.xml file.

Currently trying to find out how to work around this.  If you install Eclipse using a ZIP file instead of the installer, it uses YOUR JDK, not it's own, and, hence, the .p2 folder never gets created.

**Comment by johnbrvc** [comment]
Possible solution that would solve this issue:

1. Determine the version of the JVM that the test is running in: `System.getProperty("java.version")`
2. Search the **JAVA_HOME** and **PATH** environment variable for a compatible JDK (it had **BETTER** be there, or the tests won't work anyway).
3. Instead of using the default `LanguageAutoFill `value for the java compiler of "**javac**", we can explicitly set it to the full path of the corresponding JDK.  Of course, we only do this for the "`SampleContest`", which is used by the _JUnits_.  This way, the _JUnits_ will run on all platforms now, and going forward.

**Comment by clevengr** [comment]
While I don't pretend to yet understand all the intricacies of the issue as described, I did just run a test.  I am seeing JUnits `services.web.EventFeedLogTest` and `services.web.EventFeedFilterTest` pass when run individually, but fail when run as part of the larger `test` package.  This is consistent with the above descriptions of the issue.

_However_, I just verified that both `java` and `javac` on my machine are running Java 1.8.  That is, I see the following at a command prompt:
```
java -version
java version "1.8.0_271"
```
and
```
javac -version
javac 1.8.0_271
```
This, it seems to me, is inconsistent with the above descriptions -- that is, it seems clear that Java 1.8 IS at the front of my PATH.

**Comment by johnbrvc** [comment]
> While I don't pretend to yet understand all the intricacies of the issue as described, I did just run a test. I am seeing JUnits `services.web.EventFeedLogTest` and `services.web.EventFeedFilterTest` pass when run individually, but fail when run as part of the larger `test` package. This is consistent with the above descriptions of the issue.
> 
> _However_, I just verified that both `java` and `javac` on my machine are running Java 1.8. That is, I see the following at a command prompt:
> 
> ```
> java -version
> java version "1.8.0_271"
> ```
> 
> and
> 
> ```
> javac -version
> javac 1.8.0_271
> ```
> 
> This, it seems to me, is inconsistent with the above descriptions -- that is, it seems clear that Java 1.8 IS at the front of my PATH.

Yes, it doesn't matter, because Eclipse is using the same "java" that it is run with, not with what is on your path.  From above:

> Further research reveals the REASON that some JUnit tests were failing. It seems any test that uses the Executable class to compile and run a java program will use Eclipse's default javac compiler. 

On my system, for example, Eclipse is run using Java17, even though Java8 is on my path first.  It uses the javac/java that come with eclipse.  You can see this in Eclipse, if you go to menu: Window->Preferences->Java->Compiler, and look at the compiler compliance level (17 on mine).  Then, select the "Installed JRE's" at the same level as Compiler.  There will be one that has a long path that looks something like: C:\Users\XXXX\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.1.v20211116-1657\jre
That is the java that Eclipse runs in, and, consequently, the one that will be used when the Executable class is used to compile and run java stuff (like JUnits).
